name: Test
on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      sha:
        description: Git reference commit.
        type: string
        required: true
      push:
        description: "Push image to docker repo?"
        type: boolean
        required: true

env:
  LANG: C.UTF-8

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Set something to 'mini'
        shell: bash
        run: |
          echo "CURRENT_GIT_COMMIT=${{ github.event.pull_request.base.ref == 'releases/latest' && github.event.pull_request.head.sha || github.event.inputs.sha || github.sha}}" >> $GITHUB_ENV
      - name: 'Print result'
        run: echo $SOMETHING
